boundlessgeo/spatialconnect-android-sdk

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoJsonStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java

also camelCasing method names for consistency

use store name from config file

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStoreException.java

* refactor storeEventsSubject to use BehaviorSubject instead of
PublishSubject to make allStoresStartedObs implementation cleaner
SPACON-66
SPACON-63
SPACON-71

fixing geopackage tests to handle exceptions

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStoreException.java

* also updating scheduler to use io scheduler implementation

refactoring exception to keep the cause

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java

refactoring tests

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoJsonAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/query/SCGeometryPredicateComparison.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/query/SCPredicate.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java

adding contains filter

---

spatialconnect/build.gradle
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/BaseTestCase.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/LocationHelperTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SensorServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java

* this speeds up the tests by only initializing the instrumentation once

refactoring tests to use JUnit4 test runner

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ConfigServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCKVPStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCKVPStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCStoreConfigRepository.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/messaging/MessageType.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/messaging/SCConfigMessage.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/messaging/SCMessage.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCServiceManager.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStoreStatus.java

**READY**
This PR adds message based communication between services.  It refactors some of the tests to handle the new way the services and data stores are initialized.
```sh
git pull --prune
git checkout <feature_branch>
```
* This will mainly affect the config and data services.

adding message based communication between services

---

.travis.yml
README.md
spatialconnect/build.gradle
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCConfigServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCSqliteHelperTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SensorServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/SpatialConnect.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCJavascriptBridgeHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java

**Ready**
Renaming service manager
*  None, only renaming things in this PR 

renaming SCServiceManager to SpatialConnect

---

spatialconnect/build.gradle

READY
Change compileSdkVersion and com.bedatadriven:jackson-datatype-jts versions

Update Dependency and SDK versions

---

.travis.yml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
spatialconnect/build.gradle
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/BaseTestCase.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/DefaultStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/MultiDexAndroidJUnitRunner.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCConfigServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCKVPStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCSqliteHelperTest.java
spatialconnect/src/androidTest/res/raw/scconfig.json
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/SpatialConnect.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/LocationHelper.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCNetworkService.java

**READY**
Fixing the tests so they run on the CI
Notes regarding deployment the contained body of work. 
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
List general components of the application that this PR will affect:
* 

Fix tests on travis

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCFormConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java

**READY**
Fixes #71
Notes regarding deployment the contained body of work. 
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
List general components of the application that this PR will affect:
* 

ignore null config properties

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java
spatialconnect/src/androidTest/res/raw/scconfig.json
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCNetworkService.java

**READY**
Refactoring to read api url from config file.  Also updating endpoint to `/forms`
Notes regarding deployment the contained body of work. 
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
List general components of the application that this PR will affect:
* 

refactoring to read api url from config file

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCSpatialFeature.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCNetworkService.java

**READY**
SPACON-133
Bringing the form submission functionality to parity with spatialconnect-ios-sdk
```sh
```

Ios parity with form submission

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCSpatialFeature.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCNetworkService.java

Reverts boundlessgeo/spatialconnect-android-sdk#79
This should have been merged to develop, not master

Revert "Ios parity with form submission"

---

spatialconnect/build.gradle
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/DefaultStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCSqliteHelperTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/WFSStoreTest.java
spatialconnect/src/androidTest/res/raw/scconfig.json
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCFormConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCFormField.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoJsonAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCSqliteHelper.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCNetworkService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/DefaultStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoJsonStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

**READY**
SPACON-82
Adding WFSStore and other improvements
```sh
```
* refactoring version to use strings
* bumping version to 0.4.0
* refactoring to use new form schema

adding WFSStore

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java

**READY**
SPACON-190
Send `type` attribute when registering a device.  Also refactoring to check if the device is registered before attempting to register.  
boundlessgeo/spatialconnect-server#72 should be merged before this PR.
```sh
```

refactoring to send type when registering device

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java

adding responseId to events that need it

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java

bug fix for reloading react native js

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCFormField.java

**READY/**
SPACON-167
- Adds photo field to SCFormField

Add photo field type

---

spatialconnect/build.gradle

**READY**
Downgrades okhttp dep to 3.3.1
https://github.com/facebook/react-native/issues/9043

Downgrade okhttp

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/GeoPackage.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/GeoPackageContents.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCGpkgFeatureSource.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

**READY**
N/A
Refactoring to fix an issue with querying a GeoPackage store after WFS store ran under the `queryAllStores` method.
```sh
```

fix gpkg query

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java

**IN DEVELOPMENT**
SPACON-206
- Adds `handleQuery` to bridge
- Adds `queryStores` to DataService, which filters and queries active stores
```sh
```

Query list of stores

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java

parse feature map instead of string

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java

removing recursive call & adding debug logs

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/FormStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/LocationStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCBackendServiceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCSqliteHelperTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/ServicesTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/WFSStoreTest.java
spatialconnect/src/androidTest/res/raw/scconfig_local.json
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/HttpHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCAuthService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCSensorService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/LocationStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

**READY**
Removed http calls from backendService.  If http call is needed call http util
```sh
```

removed http calls from backendService

---

spatialconnect/build.gradle
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCConfigServiceTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCAuthService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

**READY**
SPACON-202
Adding observable to backend service to observe changes to network connectivity.
```sh
```

adding reactive network observable

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoJsonAdapter.java

renaming log tag to correct name

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/SpatialConnect.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/mqtt/MqttHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/HttpHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCAuthService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

**READY**
SPACON-220
Refactoring observables serving as boolean flags to use booleans instead of integers.  Also some other refactoring (removing unused imports & exceptions)
```sh
```

refactoring service observables to use booleans

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

Ready
Fixed JSON exception while querying the WFS Store
```sh
```

Fixed JSON parse error on WFS store query

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCConfigServiceTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

READY
EFC Android app was not loading forms on initial load.
```sh
```

Adding hasForms so forms should show on initial app load

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCAuthService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

Ready
Fail gracefully instead of crashing when http calls get unexpected results
```sh
```

Handle http error without crashing app

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

Ready
SPACON-223
Forms could not be queried.  Tested from RN app by submitting form and seeing a new pin on map.
```sh
```

Remove override to query form

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/BaseTestCase.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgTileSourceTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/SpatialConnect.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/GeoPackage.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/GeoPackageContents.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCSqliteHelper.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/HttpHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/tiles/GpkgTileProvider.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/tiles/SCGpkgTileSource.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/tiles/SCTileMatrixRow.java

**READY**
SPACON-218
Adding support for TileOverlays using tiles from a GeoPackage.
```sh
```

adding support for gpkg tiles

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java

fixing form schema parser to handle forms with no fields

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java

Ready
SPACON-151
CRUD on server dashboard should filter down to device
```sh
```

Adding CRUD for stores C2D

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/FormStoreTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgFeatureSourceTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCGpkgTileSourceTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

Ready
SPACON-155
Adding Form CRUD for C2D, also ignored test that downloaded Whitehorse geopackage until a smaller geopackage is available for testing.  Currently timeout errors occur on local machine as well as travis.
```sh
```

Adding form CRUD for C2D

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCRasterStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/tiles/GpkgRasterSource.java

**READY**
SPACON-229
Adding the raster store interface and implementation with a GeoPackage
```sh
```

adding raster store functionality

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoJsonAdapter.java

READY
SPACON-235
If uri has a http link, the sdk should download the geojson from the http url
```sh
```

Download geojson from cloud

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

Ready
SPACON-244
Ensure field keys are valid before create feature tables.
```sh
```

Ensure field keys valid before creating table

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java

Ready
SPACON-249
Ensure geo package db file names are id.gpkg
```sh
```

Ensure geo package db file names are id.gpkg

---

spatialconnect/build.gradle
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/LocationHelper.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCSensorService.java

Ready
Removing the request for gps permissions.  Host app should ensure correct permissions are set before enabling GPS.
```sh
```

Remove request for gps permissions

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoPackageAdapter.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/DefaultStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoJsonStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/LocationStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

READY
SPACON-234
stores should implement SCSpatialStore, SCRasterStore, SCDataStoreLifecycle
```sh
```

Stores implement SCSpatialStore, SCRasterStore, SCDataStoreLifecycle

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCAuthService.java

**READY**
SPACON-227 
SPACON-256
The login status should be updated even if the authentication fails.  This is how it was already implemented in the iOS SDK.  
```sh
```

update login status if authentication fails

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/mqtt/MqttHandler.java

Ready
Check if mqtt configs are ssl to add custom socket factory
```sh
```

adding ssl check for mqtt

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/mqtt/MqttHandler.java

**READY**
Fixing bug...should check protocol, not host for ssl configuration.
```sh
```

check protocol instead of host

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/dataAdapter/GeoJsonAdapter.java

**READY**
SPACON-320
When the geojson file is found, save the filePath to use later when querying
```sh
```

Set correct file path when geojson file is found

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

READY
init vector names list and clear on stop for wfs store 
```sh
```

init wfs vector layers and clear on stop

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/mqtt/SCNotification.java

**READY**
SPACON-382
Adjust to new format
```sh
```

New notification format

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java

**READY**
Fixes bug parsing the store configs with team ids.
```sh
```

update store config to parse team id

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/config/SCStoreConfig.java

**READY**
Updating the store config so it can parse store options

add options property to store config

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoJsonTest.java
spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/GeoPackageTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoJsonStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/LocationStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStoreLifeCycle.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCRemoteDataStore.java

**READY**
SPACON-346
Ensure local files for stores are removed when store is deleted.
```sh
```

Clean up store delete

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

**READY**
Fix discrepancy with[ iOS implementation ](https://github.com/boundlessgeo/spatialconnect-ios-sdk/blob/master/SpatialConnect/SCFormStore.m#L119-L125)

send form submission over mqtt after it writes to form store

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/SCCacheTest.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCBoundingBox.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCGeometry.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCGeometryCollection.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCGeometryFactory.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCSpatialFeature.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/Json/JsonUtilities.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/Json/SCObjectMapper.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java

**READY**
* Refactoring to use a single object mapper.  Also, configure this object mapper to ignore properties it does not know how to bind/parse.
* update form submission payload to match ios sdk

refactoring to use one object mapper

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/LocationStore.java

**READY**
Send altitude in location updates for [parity with ios sdk](https://github.com/boundlessgeo/spatialconnect-ios-sdk/blob/develop/SpatialConnect/SCSensorService.m#L100)

add altitude (z) to coordinate on location updates

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCConfigService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/WFSStore.java

**READY**
SPACON-390
Ensure SCConfigSvc matches iOS public methods
```sh
```

SCConfigSvc up to speed with iOS

---

SpaconApp/src/androidTest/java/com/boundlessgeo/spaconapp/test/IntegratedTests.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java

**READY**
Fix tests related to correlation id issues.  https://github.com/boundlessgeo/spatialconnect-server/pull/208 needs to be merged first

Correlation id fix

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java

**READY**
Payload in SCMessage is now valid json, per https://github.com/boundlessgeo/spatialconnect-server/pull/210
```sh
```

Payload for deleting store/form should be valid json string

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java

**READY**
SPACON-412
modify mqtt status payload to include connected object
```sh
```

Adding connected object to mqtt status payload

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCBridge.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/jsbridge/SCJavascriptBridgeHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/schema/SCCommand.java

**READY**
[SPACON-441]
- Changes the query commands from https://github.com/boundlessgeo/spatialconnect-schema/pull/9
```sh
```

[SPACON-441] Change query commands

---

SpaconApp/src/androidTest/java/com/boundlessgeo/spaconapp/test/IntegratedTests.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/scutilities/HttpHandler.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCKeyTuple.java

**READY**
SPACON-592
Fixed bug and added form submission tests using server endpoint
```sh
```

Not saving form collection

---

spatialconnect/src/androidTest/java/com/boundlessgeo/spatialconnect/test/LocationStoreTest.java

fix to wait for observable to complete before checking onNext events

---

spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/GeoPackage.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/db/SCGpkgFeatureSource.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/geometries/SCSpatialFeature.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCBackendService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/services/SCDataService.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/FormStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/GeoPackageStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/ISyncableStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/LocationStore.java
spatialconnect/src/main/java/com/boundlessgeo/spatialconnect/stores/SCDataStore.java

**READY**
SPACON-602
Adding the the ISyncableStore interface
```sh
```

Add ISyncableStore interface
